export interface IUsers {
    avatar: [string],
    userName: string,
    userAge: number,
    verification: boolean,
    location: string,
    locationFrom: string,
    userTall: number,
    gender: string,
    userDescription: string,
    userSearch: string,
    zodiac: string,
    lifeStyle: [string],
    userInterests: [string],
}